title: Jorge de la Flor
logo: /assets/img/Foto de presentación.jpg
description: Bienvenido a la presentación de mi perfil.
url: "https://jafa.dev"
baseurl: ""
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

# Snake Code Institute Configuration
sci_email: jafdelaflor@gmail.com
sci_github: https://github.com/Jorge-de-la-Flor
sci_linkedin: https://www.linkedin.com/in/jorge-de-la-flor-100950210/
sci_enroll_url: "#inscripcion"

# Puedes agregar más variables personalizadas aquí
# sci_whatsapp: "+51999999999"
sci_discord: "https://discord.gg/UFPj9mFw"
